package org.doubrava.ergologger.bl;

public enum ApplicationProperty {
    DATA_ADAPTER,
    DATA_ACTIVITY_TYPE,
    EXPORT_DIRECTORY,
    EXPORT_TXT_DELIMETER,
    EXPORT_TXT_NEWLINE,
    FORMAT_TIMESTAMP_PATTERN,
    FORMAT_TIME_PATTERN,
    FORMAT_DATE_PATTERN,
    FORMAT_LOCALE_COUNTRY,
    FORMAT_LOCALE_LANGUAGE
}
